#!/usr/bin/env bash
#
# Reads PORTMAP file and outputs -p $PORT for each private port listed there.
APP=$1
PORTMAP="$DOKKU_ROOT/PORTMAP"
ARGS=
if [[ -f "$PORTMAP" ]] ; then
  exec < "$PORTMAP"
  while read LINE ; do
    if [[ "$LINE" =~ [0-9]+: ]] ; then
      PUBLIC_PORT=${LINE%:*}
      REST=${LINE#*:}
      APP_NAME=${REST%:*}
      PRIVATE_PORT=${REST#*:}
      echo -n "-p $PRIVATE_PORT "
    fi
  done
fi
