#!/usr/bin/env bash
#
# Reads PORTS file and outputs -p $PORT for each private port listed there.
APP=$1
PORTS="$DOKKU_ROOT/$APP/PORTS"
if [[ -f "$PORTS" ]] ; then
  exec < "$PORTS"
  while read LINE ; do
    if [[ "$LINE" =~ [0-9]+: ]] ; then
      PUBLIC_PORT=${LINE%:*}
      PRIVATE_PORT=${LINE#*:}
      echo -n "-p $PRIVATE_PORT "
    fi
  done
fi
