#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
PLUGIN=$PLUGIN_PATH/$(basename $(dirname $0));

# Recent version of Node
add-apt-repository -y ppa:chris-lea/node.js 
apt-get update 
apt-get install -y nodejs

# Create init.d file with substitute values
sed -e "s|\$PLUGIN_PATH|$PLUGIN|g" \
    -e "s|\$DOKKU_ROOT|$DOKKU_ROOT|g" \
    $(dirname $0)/init > /etc/init.d/dokku-ports
chmod +x /etc/init.d/dokku-ports

if ! grep -q dokku-ports-reload "/etc/sudoers"; then
  touch /etc/sudoers.tmp
  cp /etc/sudoers /tmp/sudoers.new
  echo "%dokku ALL=(ALL)NOPASSWD:/etc/init.d/dokku-ports reload # dokku-ports-reload" >> /tmp/sudoers.new
  EDITOR="cp /tmp/sudoers.new" visudo
  rm /tmp/sudoers.new
fi

update-rc.d dokku-ports default
/etc/init.d/dokku-ports start
