#!/usr/bin/env bash
# pre-deploy extracts PORTS, post-deploy tells dokku-ports to reload
# configuration.
APP=$1
if [[ -f "$DOKKU_ROOT/$APP/PORTS" ]] ; then
  echo "-----> Reloading dokku-ports"
  sudo /etc/init.d/dokku-ports reload
fi
